### ISSUE TITLE
Partially staged files

### ISSUE THREAD

**Issue by MatthewMi11er** [azz/pretty-quick#30] opened 2018-05-19 22:02 UTC
Am I misunderstanding what is meant by partially staged files? If I stage all my changes for a commit and one of those files requires formatting, then when I run `pretty-quick --staged` it errors, doesn't restaged the file and tells me it `Found partially staged file`.  On the other hand if no staged files required formatting then it proceeds without error. 

I would have not expected this behavior unless one of the changed files had remaining unstaged changes prior to running `pretty-quick`

**Comment by azz** [comment] 2018-05-20 01:45
Sounds like a bug, cc. @mpareja.

**Comment by azz** [comment] 2018-05-20 02:15
Can't immediately reproduce this. Tried:

```shellsession
$ yarn init -y
$ yarn add -D prettier pretty-quick@1.5.0
$ git init
$ echo 'var formatted = true;' > x.js
$ echo 'var  unformatted   = true ;' > y.js
$ git add x.js y.js
$ yarn pretty-quick --staged
yarn run v1.3.2
$ /Users/azz/code/pretty-quick-issue-30/node_modules/.bin/pretty-quick --staged
🔍  Finding changed files since git revision null.
🎯  Found 2 changed files.
✍️  Fixing up y.js.
✅  Everything is awesome!
✨  Done in 0.51s.
```

**Comment by rdiazv** [comment] 2018-05-20 19:13
I have the same issue.

**Comment by marc1404** [comment] 2018-05-20 20:02
I'm using `pretty-quick@1.5.0` and I have the same problem.
```sh
error Command failed.
Exit code: 1
Command: git
Arguments: commit -m v0.0.108
Directory: ...
Output:
husky > npm run -s precommit (node v10.1.0)

🔍  Finding changed files since git revision 6c06227.
🎯  Found 1 changed file.
✍️  Fixing up package.json.
✗ Found partially staged file package.json.
✗ Partially staged files were fixed up. Please update stage before committing.

husky > pre-commit hook failed (add --no-verify to bypass)
info Visit https://yarnpkg.com/en/docs/cli/version for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by azz** [comment] 2018-05-21 12:07
Multiple reports, reverting last change in #32. Will diagnose further once the release (1.5.1) is out.

**Comment by azz** [comment] 2018-05-21 12:08
@marc1404 what was the status of `package.json` before you committed?

**Comment by azz** [comment] 2018-05-21 12:19
1.5.1 will fix the issue https://github.com/azz/pretty-quick/releases/tag/v1.5.1

**Comment by azz** [comment] 2018-05-21 12:28
If anyone is able to describe reproduction steps we should be able to fix this one and re-add the feature.

**Comment by marc1404** [comment] 2018-05-21 14:32
Thanks for reacting so quickly on this issue!
I can reproduce it on `v1.5.0` by running only `pretty-quick` (everything working) or `pretty-quick --staged` in the precommit-hook.

Here is my test *without** the `--staged` flag:
```sh
$ git diff
diff --git a/layouts/default.vue b/layouts/default.vue
index 29290c1..4b73e9d 100644
--- a/layouts/default.vue
+++ b/layouts/default.vue
@@ -29,6 +29,7 @@
 import { Navbar, Sidebar, sidebarService } from '~/src/layout';

     const test = '';
+    const test2 = '';

 export default {
     name: 'DefaultLayout',
diff --git a/package.json b/package.json
index e23dd53..cf38a12 100644
--- a/package.json
+++ b/package.json
@@ -7,7 +7,7 @@
     "scripts": {
-        "precommit": "pretty-quick --staged",
+        "precommit": "pretty-quick",
$ git commit -m "test"
husky > npm run -s precommit (node v10.1.0)

🔍  Finding changed files since git revision 4d90c6c.
🎯  Found 1 changed file.
✍️  Fixing up layouts/default.vue.
✅  Everything is awesome!
```

Here is the output **with** the `--staged` flag:
```sh
$ git diff
diff --git a/layouts/default.vue b/layouts/default.vue
index 29290c1..4b73e9d 100644
--- a/layouts/default.vue
+++ b/layouts/default.vue
@@ -29,6 +29,7 @@
 import { Navbar, Sidebar, sidebarService } from '~/src/layout';

     const test = '';
+    const test2 = '';

 export default {
     name: 'DefaultLayout',
$ git add .
$ git commit -m "test"
husky > npm run -s precommit (node v10.1.0)

🔍  Finding changed files since git revision 50d4fcf.
🎯  Found 1 changed file.
✍️  Fixing up layouts/default.vue.
✗ Found partially staged file layouts/default.vue.
✗ Partially staged files were fixed up. Please update stage before committing.

husky > pre-commit hook failed (add --no-verify to bypass)
```

**Comment by azz** [comment] 2018-05-21 22:09
`git diff` only shows unstaged files. Could you repeat the second test above but run both `git diff` and `git diff --staged`?

**Comment by marc1404** [comment] 2018-05-22 08:00
Okay, I reverted back to `v1.5.0` and did the second test again (I staged all changed files):
```sh
$ git diff
$ git diff --staged
diff --git a/layouts/default.vue b/layouts/default.vue
index d493edc..e07165e 100644
--- a/layouts/default.vue
+++ b/layouts/default.vue
@@ -28,6 +28,8 @@
 <script>
 import { Navbar, Sidebar, sidebarService } from '~/src/layout';

+    const test = '';
+
 export default {
     name: 'DefaultLayout',
     components: {
diff --git a/package.json b/package.json
index a5ad677..2bbe73d 100644
--- a/package.json
+++ b/package.json
@@ -71,7 +71,7 @@
         "minimist": "1.2.0",
         "node-notifier": "5.2.1",
         "prettier": "1.12.1",
-        "pretty-quick": "1.5.1"
+        "pretty-quick": "1.5.0"
     },
     "engines": {
         "node": ">=9.0.0",
diff --git a/yarn.lock b/yarn.lock
index 3123e2d..a0ba45b 100644
--- a/yarn.lock
+++ b/yarn.lock
@@ -4491,9 +4491,9 @@ pretty-ms@3.1.0:
     parse-ms "^1.0.0"
     plur "^2.1.2"

-pretty-quick@1.5.1:
-  version "1.5.1"
-  resolved "https://registry.yarnpkg.com/pretty-quick/-/pretty-quick-1.5.1.tgz#b36bb4fe7cdb04ed5f4ba4ba530d609cb3be4ac2"
+pretty-quick@1.5.0:
+  version "1.5.0"
+  resolved "https://registry.yarnpkg.com/pretty-quick/-/pretty-quick-1.5.0.tgz#304853ece7f8cb56bec74ba3ccd978037e7f2117"
   dependencies:
     chalk "^2.3.0"
     execa "^0.8.0"
mbp-mv:BLS_Dashboards marc$ git commit -m "test"
husky > npm run -s precommit (node v10.1.0)

🔍  Finding changed files since git revision 018df2d.
🎯  Found 2 changed files.
✍️  Fixing up layouts/default.vue.
✗ Found partially staged file layouts/default.vue.
✗ Partially staged files were fixed up. Please update stage before committing.

husky > pre-commit hook failed (add --no-verify to bypass)
```

**Comment by mpareja** [comment] 2018-05-22 14:09
Okay, I have a reproduction and I think I have line-of-sight on the issue. I'll keep you posted.

**Comment by azz** [comment] 2018-05-22 14:11
Thanks for investigating!

**Closed** 2018-05-22 22:28 UTC
Labels: bug

**Comment by azz** [comment] 2018-05-22 22:29
Thank you @mpareja. Reason I couldn't repro is I tried from a fresh git repo, whose `revision` is `null`. 

1.6.0 will re-introduce this feature.

**Comment by mpareja** [comment] 2018-05-23 13:15
The new version is out. Can you give that a go @MatthewMi11er, @marc1404 and @rdiazv ?

**Comment by marc1404** [comment] 2018-05-23 13:23
@mpareja Working out perfectly so far on `1.6.0`!
Thank you all :)

**Comment by MatthewMi11er** [comment] 2018-05-24 01:45
`1.6.0` seems to work correctly for me! Thanks for fixing that!

**Comment by sultanassi95** [comment] 2019-12-09 14:48
**Removing** `yarn.lock` and running `yarn install` solved my problem.

Error Message:
```
✖ pretty-quick --staged found some errors. Please fix them and try committing again.
🔍  Finding changed files since git revision 871be03.
🎯  Found 32 changed files.
✍️  Fixing up src/actions/index.ts.
/home/sultan/Desktop/masterworks/pplus-admin-panel/node_modules/pretty-quick/node_modules/execa/index.js:201
		throw error;
		^

Error: Command failed with exit code 128 (Unknown system error -128): git add src/actions/index.ts
  at makeError (/home/sultan/Desktop/masterworks/pplus-admin-panel/node_modules/pretty-quick/node_modules/execa/lib/error.js:59:11)
  at Function.module.exports.sync (/home/sultan/Desktop/masterworks/pplus-admin-panel/node_modules/pretty-quick/node_modules/execa/index.js:187:17)
  at runGit (/home/sultan/Desktop/masterworks/pplus-admin-panel/node_modules/pretty-quick/dist/scms/git.js:42:52)
  at Object.stageFile (/home/sultan/Desktop/masterworks/pplus-admin-panel/node_modules/pretty-quick/dist/scms/git.js:79:3)
  at onWriteFile (/home/sultan/Desktop/masterworks/pplus-admin-panel/node_modules/pretty-quick/dist/index.js:70:15)
  at _default (/home/sultan/Desktop/masterworks/pplus-admin-panel/node_modules/pretty-quick/dist/processFiles.js:46:22)
  at _default (/home/sultan/Desktop/masterworks/pplus-admin-panel/node_modules/pretty-quick/dist/index.js:58:29)
  at Object.<anonymous> (/home/sultan/Desktop/masterworks/pplus-admin-panel/node_modules/pretty-quick/bin/pretty-quick.js:12:27)
  at Module._compile (internal/modules/cjs/loader.js:778:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
husky > pre-commit hook failed (add --no-verify to bypass)
```

**Comment by JonathanDCohen** [comment] 2020-03-16 17:45
I'm getting this error in v2.0.1 when I have no partially staged files, just one file in staging

**Comment by danielmeyer-cn** [comment] 2020-06-05 13:17
Same for me. In v2.0.1 I'm getting this error om some random files. If i change to v1.5.1 it's working.

**Comment by SudoPlz** [comment] 2021-06-02 14:15
Same

**Comment by AllanOricil** [comment] 2021-06-04 19:04
Im facing the same problem with 2.0.1

**Comment by AllanOricil** [comment] 2021-06-04 19:26
After updating to 3.1.0 the issue is gone

**Comment by AntonGrekov** [comment] 2023-07-19 19:47
Same problem on 3.1.3
